package com.bjpowernode.exception;

/**
 * 异常：当代码中发生了异常，虚拟机会中断程序的执行，后面的代码就没办法运行了。。
 */
public class Test04 {
    public static void main(String[] args) {
        System.out.println(10 / 0);

        System.out.println("===============");
    }
}
